### ISSUE TITLE
Label leakage during zero-shot evaluation of Classification and NLI datasets

### ISSUE THREAD

**Issue by adivekar-utexas** [jiacheng-ye/ZeroGen#2]
Hi. From my understanding, there could be a label leakage in the prompt when doing zero-shot evaluation with Classification and NLI datasets?

I am seeing in the code, the following prompts are used (using `imdb-zero-shot.json` as an example):

* Positive (label=0)
```The movie review in positive sentiment is: "<X>"```

* Negative (label=1)
```The movie review in negative sentiment is: "<X>"```
where `<X>` is replaced with the movie review, before feeding it to GPT-2. 

The words "positive" and "negative" are not replaced. This is seems like label leakage. I don't see any code where this is removed in the zero-shot baseline  

So it seems to me like the Prompting baseline in ZeroGen is incorrect and overestimates the true value.

Would love to hear your thoughts.

**Comment by jiacheng-ye** [comment]
Sorry for the late reply. Thanks for your question!
Actually, when doing classification for sentence X, we calculate the PPL of both sentences (i.e., `The movie review in positive sentiment is: "<X>"` and `The movie review in negative sentiment is: "<X>"`) and select the one with lower PPL as the answer, instead of *generating* a label. This alleviates the problem of not generating label-related words.
Similar idea can be found in the original [GPT-3 paper ](https://arxiv.org/pdf/2005.14165.pdf) (section 2.4)
Here is the related code in ZeroGen: https://github.com/HKUNLP/ZeroGen/blob/0581de739a35b7bc4a0f533adea20b2830a694fa/cls_generator.py#L107

**Comment by jiacheng-ye** [comment]
Closed for now, feel free to reopen!
